### ISSUE TITLE
I can log into your application

### ISSUE THREAD

**Issue by dubulahla2** [Itshyphen/Blockchain#4]
Hi there please assist me in login into you Web Application, I can approve on metaMask but it does not move to another page like patient page .  I know i dont know you but if i could have a zoom meeting with you it would really help me out .

**Comment by Itshyphen** [comment]
> Hi there please assist me in login into you Web Application, I can approve on metaMask but it does not move to another page like patient page . I know i dont know you but if i could have a zoom meeting with you it would really help me out .

Yess, you can find me on discord Ranju#1123
